#
# Generated by ./regions.tf.sh
# Do not directly modify this file
#

module "us-east-1" {
  aws_region = "us-east-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "us-east-2" {
  aws_region = "us-east-2"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "us-west-1" {
  aws_region = "us-west-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "us-west-2" {
  aws_region = "us-west-2"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ca-central-1" {
  aws_region = "ca-central-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "eu-central-1" {
  aws_region = "eu-central-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "eu-west-1" {
  aws_region = "eu-west-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "eu-west-2" {
  aws_region = "eu-west-2"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "eu-west-3" {
  aws_region = "eu-west-3"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "eu-north-1" {
  aws_region = "eu-north-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ap-northeast-1" {
  aws_region = "ap-northeast-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ap-northeast-2" {
  aws_region = "ap-northeast-2"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ap-southeast-1" {
  aws_region = "ap-southeast-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ap-southeast-2" {
  aws_region = "ap-southeast-2"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "ap-south-1" {
  aws_region = "ap-south-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
module "sa-east-1" {
  aws_region = "sa-east-1"

  source = "./regional"

  enable = var.enable
  envname = var.envname
  lambda_notify_to_slack_arn = module.lambda_sns_to_slack.lambda_arn
  is_enable_lambda_notify_to_slack = var.guardduty_slack_webhook_url == "" ? false : true
  ipset_location = local.ipset_location
  is_enable_gurdduty_ipset = length(var.trusted_ip_cidr_blocks) > 0 ? true : false
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  tags = var.tags
}
